title: Healthier SG
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#2567cb"
  secondary-color: "#0b449f"
  media-colors:
    - title: media-color-one
      color: "#2567cb"
    - title: media-color-two
      color: "#85b2f5"
    - title: media-color-three
      color: "#11346b"
    - title: media-color-four
      color: "#102a52"
    - title: media-color-five
      color: "#0b449f"
resources_name: resource
description: Towards a Healthier Singapore
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://moh-healthiersg-staging.netlify.app
prod: https://moh-healthiersg-prod.netlify.app
is_government: true
shareicon: /images/MOHShareicon.png
google_analytics: G-T7RVVLC2DX
